### ISSUE TITLE
Summary: Meets expectations

### ISSUE THREAD

**Issue by zannain** [Craft4Coffee/jammming#11]
Great work on resolving a lot of the errors I saw earlier when I first tried to review this project! You're on the right track in regards to understanding the bigger concepts such as updating state and props. I would recommend taking the time to familiarize yourself with developer tools as they will really help ensure that everything is working as expected. It's much easier to figure out why something is not working when you can step through each line of code. 

React is a library that has a lot of development behind it so newsletters are also a great way to keep up with the changes. One of the most challenging parts of development is keeping up with these changes and it's something I recommend you do regularly to keep pace with the industry. Here are a few resources to help you with this:

1. Check out this [newsletter that was designed for developers](https://cooperpress.com/). 
2. React 16.3 was recently released with some really cool features such as the Context API which improves upon Reacts current method of state management. I recommend checking out this [article](https://auth0.com/blog/whats-new-in-react-16-3/) to learn more about the changes in 16.3 and see if you can implement them into this project.  
3. A few React-specific resources I recommend looking into to help you stay up to date is the [Syntax.fm podcast](https://syntax.fm/)
4.  I also suggest reading up on [React style guide ](https://github.com/airbnb/javascript/tree/master/react) as this will help you incorporate best practices when writing React code. 

Feel free to reach out on Slack if you have any further questions and keep up the learning!

**Comment by Craft4Coffee** [comment]
Thank you! :)
